#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : python-digitalocean
Version  : 1.14.0
Release  : 5
URL      : https://github.com/koalalorenzo/python-digitalocean/archive/v1.14.0.tar.gz
Source0  : https://github.com/koalalorenzo/python-digitalocean/archive/v1.14.0.tar.gz
Summary  : digitalocean.com API to manage Droplets and Images
Group    : Development/Tools
License  : LGPL-3.0
Requires: python-digitalocean-license = %{version}-%{release}
Requires: python-digitalocean-python = %{version}-%{release}
Requires: python-digitalocean-python3 = %{version}-%{release}
Requires: jsonpickle
Requires: requests
Requires: responses
BuildRequires : buildreq-distutils3
BuildRequires : jsonpickle
BuildRequires : requests
BuildRequires : responses

%description
python-digitalocean
===================

This library provides easy access to Digital Ocean APIs to deploy
droplets, images and more.

|image0|

| |image1|
| |image2|
| |image3|

How to install
--------------

You can install python-digitalocean using **pip**

::

    pip install -U python-digitalocean

or via sources:

::

    python setup.py install

Features
--------

python-digitalocean support all the features provided via
digitalocean.com APIs, such as:

-  Get user's Droplets
-  Get user's Images (Snapshot and Backups)
-  Get public Images
-  Get Droplet's event status
-  Create and Remove a Droplet
-  Resize a Droplet
-  Shutdown, restart and boot a Droplet
-  Power off, power on and "power cycle" a Droplet
-  Perform Snapshot
-  Enable/Disable automatic Backups
-  Restore root password of a Droplet

 Examples
---------

Listing the droplets
~~~~~~~~~~~~~~~~~~~~

This example shows how to list all the active droplets:

.. code:: python

    import digitalocean
    manager = digitalocean.Manager(token="secretspecialuniquesnowflake")
    print(manager.get_all_droplets())

Shutdown all droplets
~~~~~~~~~~~~~~~~~~~~~

This example shows how to shutdown all the active droplets:

.. code:: python

    import digitalocean
    manager = digitalocean.Manager(token="secretspecialuniquesnowflake")
    my_droplets = manager.get_all_droplets()
    for droplet in my_droplets:
        droplet.shutdown()

Creating a Droplet and checking its status
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

This example shows how to create a droplet and how to check its status

.. code:: python

    import digitalocean
    droplet = digitalocean.Droplet(token="secretspecialuniquesnowflake",
                                   name='Example',
                                   region='nyc2', # New York 2
                                   image='ubuntu-14-04-x64', # Ubuntu 14.04 x64
                                   size_slug='512mb',  # 512MB
                                   backups=True)
    droplet.create()

Checking the status of the droplet
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

.. code:: python

    actions = droplet.get_actions()
    for action in actions:
        action.load()
        # Once it shows complete, droplet is up and running
        print action.status

Add SSHKey into DigitalOcean Account
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

.. code:: python

    from digitalocean import SSHKey

    user_ssh_key = open('/home/<$USER>/.ssh/id_rsa.pub').read()
    key = SSHKey(token='secretspecialuniquesnowflake',
                 name='uniquehostname',
                 public_key=user_ssh_key)
    key.create()

Creating a new droplet with all your SSH keys
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

.. code:: python

    manager = digitalocean.Manager(token="secretspecialuniquesnowflake")
    keys = manager.get_all_sshkeys()

    droplet = digitalocean.Droplet(token="secretspecialuniquesnowflake",
                                   name='DropletWithSSHKeys',
                                   region='ams3', # Amster
                                   image='ubuntu-14-04-x64', # Ubuntu 14.04 x64
                                   size_slug='512mb',  # 512MB
                                   ssh_keys=keys, #Automatic conversion
                                   backups=False)
    droplet.create()

Testing
-------

Test using Docker
~~~~~~~~~~~~~~~~~

To test this python-digitalocean you can use
`docker <https://www.docker.com>`__ to have a **clean environment
automatically**. First you have to build the container by running in
your shell on the repository directory:

::

    docker build -t "pdo-tests" .

Then you can run all the tests (for both python 2 and python 3)

::

    docker run pdo-tests

**Note**: This will use Ubuntu 14.04 as base and use your repository to
run tests. So every time you edit some files, please run these commands
to perform tests on your changes.

Testing using pytest manually
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Use `pytest <http://pytest.org/>`__ to perform testing. It is
recommended to use a dedicated virtualenv to perform tests, using these
commands:

::

    $ virtualenv /tmp/digitalocean_env
    $ source /tmp/digitalocean_env/bin/activate
    $ pip install -r requirements.txt

To run all the tests manually use py.test command:

::

    $ python -m pytest

Links
-----

-  GitHub: https://github.com/koalalorenzo/python-digitalocean
-  PyPI page: https://pypi.python.org/pypi/python-digitalocean/
-  Author Website:
   `http://who.is.lorenzo.setale.me/? <http://setale.me/>`__
-  Author Blog: http://blog.setale.me/

.. |image0| image:: https://travis-ci.org/koalalorenzo/python-digitalocean.svg
   :target: https://travis-ci.org/koalalorenzo/python-digitalocean
.. |image1| image:: https://img.shields.io/github/forks/badges/shields.svg?style=social&label=Fork
   :target: https://travis-ci.org/koalalorenzo/python-digitalocean
.. |image2| image:: https://img.shields.io/github/stars/badges/shields.svg?style=social&label=Star
   :target: https://travis-ci.org/koalalorenzo/python-digitalocean
.. |image3| image:: https://img.shields.io/github/watchers/badges/shields.svg?style=social&label=Watch
   :target: https://travis-ci.org/koalalorenzo/python-digitalocean

%package license
Summary: license components for the python-digitalocean package.
Group: Default

%description license
license components for the python-digitalocean package.


%package python
Summary: python components for the python-digitalocean package.
Group: Default
Requires: python-digitalocean-python3 = %{version}-%{release}

%description python
python components for the python-digitalocean package.


%package python3
Summary: python3 components for the python-digitalocean package.
Group: Default
Requires: python3-core
Provides: pypi(python-digitalocean)

%description python3
python3 components for the python-digitalocean package.


%prep
%setup -q -n python-digitalocean-1.14.0
cd %{_builddir}/python-digitalocean-1.14.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1583211814
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}$(python -c "import sys; print(sys.path[-1])") python setup.py test || :
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/python-digitalocean
cp %{_builddir}/python-digitalocean-1.14.0/LICENSE.txt %{buildroot}/usr/share/package-licenses/python-digitalocean/c09f9595f49b611cb4815dac18057910e5ff66b3
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/python-digitalocean/c09f9595f49b611cb4815dac18057910e5ff66b3

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
